sonar.projectKey=frontend
sonar.projectName=Frontend
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,.github/**,vite.config.js,index.html
sonar.javascript.node.max_old_space_size=4096
sonar.sourceEncoding=UTF-8
